// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Protests.Data.Database;

namespace Protests.Data.Migrations
{
    [DbContext(typeof(ProtestsContext))]
    [Migration("20200727090622_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Protests.Data.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityName = "Zagreb",
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 43, DateTimeKind.Local).AddTicks(5250)
                        },
                        new
                        {
                            Id = 2L,
                            CityName = "Široki",
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 54, DateTimeKind.Local).AddTicks(5210)
                        });
                });

            modelBuilder.Entity("Protests.Data.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)")
                        .HasMaxLength(2048);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProtestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProtestId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CommentText = "Comment 1",
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(8960),
                            ProtestId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CommentText = "Comment 1",
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(9890),
                            ProtestId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CommentText = "Comment 1",
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(9920),
                            ProtestId = 2L
                        });
                });

            modelBuilder.Entity("Protests.Data.Entities.Organizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(2680),
                            Name = "David"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(3540),
                            Name = "SDP"
                        });
                });

            modelBuilder.Entity("Protests.Data.Entities.Protest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<long>("OrganizerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Protests");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityId = 1L,
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(5090),
                            Description = "Description 1",
                            OrganizerId = 1L,
                            StartsAt = new DateTime(2020, 8, 1, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(6070),
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2L,
                            CityId = 2L,
                            CreatedAt = new DateTime(2020, 7, 27, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(7520),
                            Description = "Description 2",
                            OrganizerId = 2L,
                            StartsAt = new DateTime(2020, 8, 11, 11, 6, 22, 56, DateTimeKind.Local).AddTicks(7560),
                            Title = "David predvodi u Širokom prosvjed"
                        });
                });

            modelBuilder.Entity("Protests.Data.Entities.Comment", b =>
                {
                    b.HasOne("Protests.Data.Entities.Protest", "Protest")
                        .WithMany("Comments")
                        .HasForeignKey("ProtestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Protests.Data.Entities.Protest", b =>
                {
                    b.HasOne("Protests.Data.Entities.City", "City")
                        .WithMany("Protests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Protests.Data.Entities.Organizer", "Organizer")
                        .WithMany("Protests")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
